### PR TITLE
#156853500 React frontend

### PR DESCRIPTION
**Pull request by otseobande**
#### What does this PR do?
- Converts the templates to react

#### Description of Task to be completed?

- convert homepage 
- convert login page
- convert signup page
- convert customer menu page
- convert customer order history page
- convert manage-menus page for caterers
- convert manage-meals page for caterers
- convert manage-orders page for caterers

#### How should this be manually tested?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Any background context you want to add?
N/A
#### Screenshots
N/A

### CODE REVIEW

**Review by Hasstrup — COMMENTED** [review]
Umm. so I think you should adhere to the redux way of writing containers and components. Leaving components to be pure, dummy and functional; nesting them in containers instead

**Comment by Hasstrup** [comment]
Great work Otse on converting your templates to React, you have shown great attention to details with the way the files are structured. I employ to keep that up. 
Important to commend you on the way you make your async requests to the Api, you have chosen to follow conventions suggested in the redux documentation, moving forward, endeavor to keep to this behavior and build on it as these tiny things that help distinguish world-class developers from the rest.
Nice work again.

**Comment by iverenshaguy** [comment]
Well done! I am impressed by how well you have adhered to the Single Responsibility Principle by using utility functions to ensure separation of concerns. This has made your code readable and easy to understand. I ask you to keep up the good work and improve on your ability to write modularized code. This will ensure that your code is easier to understand, test and refactor. You have done an amazing job.

**Review by iverenshaguy — APPROVED** [review]
Well done! I am impressed by how well you have adhered to the Single Responsibility Principle by using utility functions to ensure separation of concerns. This has made your code readable and easy to understand. I ask you to keep up the good work and improve on your ability to write modularized code. This will ensure that your code is easier to understand, test and refactor. You have done an amazing job.

**Comment by otseobande** [comment]
Thanks Iveren for your feedback. I'll continue adhering to the Single Responsibility Principle and I hope to make my codebase even easier to understand.

**Pull request merged**
